### ISSUE TITLE
`docker compose up --build` doesn't produce a working demo from a freshly cloned repo

### ISSUE THREAD

**Issue by jfuerth** [DataBiosphere/data-explorer#94]
Hi there,

I was just taking data-explorer for a test drive and I encountered an error when trying to start it up for the first time. I've managed to work around the issue but I just wanted to let you know.

Steps to reproduce:
1. `git clone git@github.com:DataBiosphere/data-explorer.git`
1. `cd data-explorer`
1. `docker-compose up --build`
1. Visit http://localhost:4400/ in a browser

Expected behaviour:
1. The Data Explorer UI appears in the browser

Actual behaviour:
1. The browser displays an HTTP 502 error from nginx
1. The following error appears in the docker-compose terminal:
```
ui_1               | /ui/node_modules/react-scripts/scripts/start.js:19
ui_1               |   throw err;
ui_1               |   ^
ui_1               | 
ui_1               | Error: Cannot find module './lib/encoding'
ui_1               |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
ui_1               |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
ui_1               |     at Module.require (internal/modules/cjs/loader.js:637:17)
ui_1               |     at require (internal/modules/cjs/helpers.js:20:18)
ui_1               |     at loadModule (/ui/node_modules/negotiator/index.js:108:16)
ui_1               |     at Negotiator.encodings (/ui/node_modules/negotiator/index.js:56:28)
ui_1               |     at Accepts.encoding.Accepts.encodings (/ui/node_modules/accepts/index.js:143:26)
ui_1               |     at ServerResponse.onResponseHeaders (/ui/node_modules/compression/index.js:178:27)
ui_1               |     at ServerResponse.writeHead (/ui/node_modules/on-headers/index.js:46:16)
ui_1               |     at ServerResponse._implicitHeader (_http_server.js:199:8)
ui_1               |     at ServerResponse.end (/ui/node_modules/compression/index.js:103:14)
ui_1               |     at ServerResponse.send (/ui/node_modules/express/lib/response.js:221:10)
ui_1               |     at processRequest (/ui/node_modules/webpack-dev-middleware/middleware.js:86:22)
ui_1               |     at Object.ready (/ui/node_modules/webpack-dev-middleware/lib/Shared.js:166:29)
ui_1               |     at Object.handleRequest (/ui/node_modules/webpack-dev-middleware/lib/Shared.js:209:10)
ui_1               |     at /ui/node_modules/webpack-dev-middleware/middleware.js:44:11
nginx_proxy_1      | 172.18.0.1 - - [09/Jul/2018:19:49:24 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
ui_1               | npm ERR! code ELIFECYCLE
ui_1               | npm ERR! errno 1
ui_1               | npm ERR! data-explorer@0.1.0 start: `PORT=4400 react-scripts start`
ui_1               | npm ERR! Exit status 1
ui_1               | npm ERR! 
ui_1               | npm ERR! Failed at the data-explorer@0.1.0 start script.
ui_1               | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ui_1               | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
ui_1               | 
ui_1               | npm ERR! A complete log of this run can be found in:
ui_1               | npm ERR!     /root/.npm/_logs/2018-07-09T19_49_24_288Z-debug.log
```

Known workaround:
- run `npm install` in the `ui/` subdirectory, then cd back to the root of the project and run `docker-compose up`

**Comment by jfuerth** [comment]
Hi, thanks for the quick response!

I'm on a Mac (OS X 10.13.5; Docker 18.03.1-ce-mac65 (24312); Compose 1.21.1).

I didn't have to change `vm.max_map_count` to get things up and running with the built-in test data. I'm currently working on loading a larger dataset into Elasticsearch to see how it looks in the explorer. I'll let you know if I run into that issue.

As for not being able to reproduce the issue, is it possible the Docker build used a cached copy of the ui? I will try to reproduce the issue tomorrow and get back to you.
